### PR TITLE
adds list_of

### PR DESCRIPTION
**Pull request by FrancescElies**
Hi, this PR adds `list_of` to validators https://github.com/hynek/attrs/issues/39

### CODE REVIEW

**Comment by FrancescElies** [comment]
Oops, Failing for some python versions

**Comment by FrancescElies** [comment]
closing, if at some point someone finds it useful feel free to reopen

**Comment by hynek** [comment]
To be clear: it's not that we're not grateful about your contribution.  We're just in the process of figuring out whether to implement those functions ourselves or use a third party (testtools/pyhamcrest).

 I'm sorry I haven't communicated it clearly as such.  My FOSS time is a bit limited ATM due to increased work load. :(

**Comment by FrancescElies** [comment]
Hey no worries, all fine, I saw another issue about testtools/pyhamcrest, but I thought that in the meanwhile one could have something less powerful but maybe useful.

By the way I really like the library

**Pull request closed without merging**
