### PR TITLE
Make Attribute instances immutable and slotted.

### PR DESCRIPTION
**Pull request by Tinche**
If this looks good to you, I'll add something to the changelog. Since the docs already define Attributes are read-only, this should be backwards compatible.

### CODE REVIEW

**Comment by hynek** [comment]
Yeah, I was always very explicit about this stuff being read-only so I’m not concerned.  As for changelog, maybe just add the function names and the PR# to the existing “faster” entry?

**Comment by Tinche** [comment]
Ping.

**Comment by hynek** [comment]
I’m conflicted about `_fast_attrs_iterate`.  Maybe kill it off but don’t use fields in internal functions and just grab `__attrs__attrs__` ?  Because the new version *is* a slowdown due to the safety checks which we don’t need internally…

By which I mean: `asdict` → use fields.  `_convert` → `__attrs_attrs__`. Does that make sense?

**Comment by Tinche** [comment]
Agreed. (Pushed the change.)

fields() will give a proper error message if junk is passed in, but with a tiny slowdown. _convert can avoid the check. Other internal functions were already using the field directly.

**Comment by hynek** [comment]
Thanks!

**Comment by Tinche** [comment]
❇️❤️

**Pull request merged**
