### PR TITLE
Implement by_name

### PR DESCRIPTION
**Pull request by hynek**
As a replacement for C.attribute that doesn't work with __slots__ and is
overall bad design.

I’ve also improved the overall exception situation (and its documentation).  Comments anyone?

### CODE REVIEW

**Comment by hynek** [comment]
This sort-of fixes #82.

**Comment by Tinche** [comment]
A thought. What about instead of __attrs_attrs__  being a tuple of Attributes, we make it an ordered dictionary of attribute names to attributes?

It's an internal thing, and fields() can be changed to just return list(__attrs_attrs__.values()) or something.

**Comment by Tinche** [comment]
Or, since I'm brainstorming, a namedtuple. That might even give us a prettier API than the dict-like by_name.

**Comment by Tinche** [comment]
If it's a namedtuple, you could do both:

```
for a in fields(C):
    pass
```

and

```
my_attr = fields(C).my_attr
```
(Again, just brainstorming, it's too early for me :p)

**Comment by hynek** [comment]
I kind of forgot, that the whole point of `fields()` is to enable us to do such changes. :D 

The irony of using `namedtuple`s within attrs is left to the reader.

**Comment by Tinche** [comment]
The thought of using an `attrs` slot class here did cross my mind, but I was afraid of attrs-ception.

However, `namedtuples` can't have fields beginning with underscore, and we obviously support attributes with names beginning with underscore. This limitation is probably so you can't clash with a method name, like `_asdict`, `_make` or `_replace`. We are of course better than namedtuple and don't make our users deal with this crap.

I like the API a lot, so let me play around with it, implement it another way.

**Comment by hynek** [comment]
OK the new API is

cr58n9nwiaapzm0

**Pull request merged**
