### PR TITLE
ENH: query attributes through private API to speed up validate.

### PR DESCRIPTION
**Pull request by cournape**
Proposal fix for #28

### CODE REVIEW

**Comment by hynek** [comment]
Thanks!

So since the tests didn’t use to cover the error before (it came thru `fields`), the coverage sank.

But since the ValueError wasn’t documented before, but OTOH the docs explicitly ask for a decorated instance, I’m tending to not handle  that special case at all.

**Comment by hynek** [comment]
you may want to use the delay I explained in the other ticket to add yourself to AUTHORS.rst and add the change to the changelog.  Thanks!

**Comment by cournape** [comment]
I did, though it seems a bit of a steal given the trivial contribution :)

**Comment by hynek** [comment]
I have a simple “every change is scared” policy. :)  Also not the code alone counts but also the way there.  A good bug report is +Inf times better than a half-assed patch.

That said, you forgot the changelog entry. :D  (`docs/changelog.rst`)

**Comment by cournape** [comment]
here we go. Hope you had a good time in Tokyo !

**Comment by hynek** [comment]
It was…intense. :)

Thanks!

**Comment by cournape** [comment]
@hynek is there something I can help w/ to make `15.2.0` happen ?

**Comment by hynek** [comment]
I’m doing some repo janitoring right now and will release afterwards.

**Pull request merged**
